### ISSUE TITLE
예제 접속 링크 확인 부탁드립니다

### ISSUE THREAD

**Issue by choies0** [WooyeongCho/CrispyJS#1]
**CrispyJS.md** 에서 **localhost:3000/playground** 링크로 가라고 안내하던데 _“***localhost*** 에서 연결을 ***거부***했습니다.”_ 라고 오류 메세지가 뜹니다.
***3000***포트로 열린 것이 맞나요?
답변 부탁드립니다.

**Comment by WooyeongCho** [comment]
수정 했습니다 다시 들어가보세요

**Comment by choies0** [comment]
수정 감사합니다!
